[password]          # Password settings
min_length = 8
max_length = 64
hash_length = 60

[salt]              # Salt setting
default_iteration = 12
min_iteration = 1
max_iteration = 31
default_prefix = '2b'
allowed_prefix = ['2a', '2b', '2y']

[encoding]          # Encoding type settings
default_type = 'utf-8'
allowed_type = ['utf-8', 'utf-16']
